[features]
seeds = false
skip-lint = false

[programs.localnet]
e_vault = "8CfypLbwEu87YxT54Jcjx3SEXLqpiHAmjmyKb86o5iHW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Admin\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
